[package]
name = "echo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.204", features = ["derive"] }
